project:
  type: website

website:
  title: "Spiritum Duo"
  site-url: "https://spiritumduo.com/"
  favicon: media/spiritum-duo-logo.png

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    toc: true



