---
title: "Spiritum Duo Landing page"
---

Well first of all, Spiritum Duo is Latin for ‘breath’ and ‘two’. What happened to ‘Spiritum Uno’ then you may ask? Well ‘Spiritum’, the first database that I built for my clinical team, was a Microsoft Access 2009 relational database. It was a steep learning cruve. I had never build a database before. I bought the Microsoft Access database for dummies e-book, including the same line of books for VBA (visual basics for applications). I was asked to build this new database after my colleagues saw what other kind of programming I could do (happy to discuss further if anyone is interested). The issue was we had a huge backlog of sleep patients, lots of poorly managed spreadsheets and lots of patients breeching. So, over the year of 2019 I learnt about Access and VBA and built a database for our local sleep service (for which I work in as a sleep specialist) basically in my spare time. It went live in Jan 2020. Then COVID hit! I never found out if all the work I put into building this database actually helped reduce the waiting times for my patients, as the sleep service was shut due to COVID for several months. Anyway, when the sleep service opened again, the department seemed to imbrace the new ‘Spiritum’ database, and they have been using it since. I also put some robotic process automation into the database to speed up tedious and error-prone tasks.

So now the respiratory team have started looking at improve the lung cancer pathway. They have asked me to start work on a new digitise and automated lung cancer pathway. I am excited about the benefit such a system can bring. I get to make more interesting programs, that do interesting things and that can actually help clinicians, admin staff and patients.

I have decided to make this a modular and open-source build, so that other disease sites and trusts (UK and abroad) could benefit from this body of work.

I will keep you informed.